[package]
name = "cuthc"
version = "0.1.0"
edition = "2021"
build="build.rs"

[build-dependencies]
cmake = "0.1.45"

[dependencies]
cudarc = { version = "0.13.4", features = ["cuda-12040"]}
cuthc_macro = { path = "../cuthc_macro" }

